version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongo-db-blog
    environment:
      - MONGO_INITDB_ROOT_DATABASE=blog-graphql
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_mongo
    volumes:
      - ./db/mongo:/data/mongodb
    ports:
      - 27017:27017
